/**
 * US classroom pronunciations, written so English TTS says the sound
 * instead of guessing from spelling (Lead → "leed", Yttrium → "yit-ree-um").
 * Names match `ELEMENTS` (Aluminum, Cesium, Sulfur).
 */
export const ELEMENT_PRONUNCIATIONS: Record<string, string> = {
  Hydrogen: "high druh jen",
  Helium: "hee lee um",
  Lithium: "lith ee um",
  Beryllium: "buh rill ee um",
  Boron: "bore on",
  Carbon: "kar bun",
  Nitrogen: "nigh truh jen",
  Oxygen: "ox ih jen",
  Fluorine: "floor een",
  Neon: "nee on",
  Sodium: "so dee um",
  Magnesium: "mag nee zee um",
  Aluminum: "uh loo mih num",
  Silicon: "sill ih kon",
  Phosphorus: "foss fer us",
  Sulfur: "sul fer",
  Chlorine: "klor een",
  Argon: "ar gon",
  Potassium: "puh tass ee um",
  Calcium: "kal see um",
  Scandium: "skan dee um",
  Titanium: "tye tay nee um",
  Vanadium: "vuh nay dee um",
  Chromium: "kroh mee um",
  Manganese: "man guh neez",
  Iron: "eye urn",
  Cobalt: "koh balt",
  Nickel: "nick ul",
  Copper: "kop er",
  Zinc: "zink",
  Gallium: "gal ee um",
  Germanium: "jer may nee um",
  Arsenic: "ar suh nick",
  Selenium: "suh lee nee um",
  Bromine: "bro meen",
  Krypton: "krip ton",
  Rubidium: "roo bid ee um",
  Strontium: "stron shee um",
  Yttrium: "it tree um",
  Zirconium: "zur koh nee um",
  Niobium: "nye oh bee um",
  Molybdenum: "muh lib duh num",
  Technetium: "teck nee shee um",
  Ruthenium: "roo thee nee um",
  Rhodium: "roh dee um",
  Palladium: "puh lay dee um",
  Silver: "sil ver",
  Cadmium: "cad mee um",
  Indium: "in dee um",
  Tin: "tin",
  Antimony: "an tih moh nee",
  Tellurium: "teh lure ee um",
  Iodine: "eye uh dine",
  Xenon: "zee non",
  Cesium: "see zee um",
  Barium: "bair ee um",
  Lanthanum: "lan thuh num",
  Cerium: "seer ee um",
  Praseodymium: "pray zee oh dim ee um",
  Neodymium: "nee oh dim ee um",
  Promethium: "pruh mee thee um",
  Samarium: "suh mair ee um",
  Europium: "yoo roh pee um",
  Gadolinium: "gad uh lin ee um",
  Terbium: "tur bee um",
  Dysprosium: "dis proh zee um",
  Holmium: "hole mee um",
  Erbium: "ur bee um",
  Thulium: "thoo lee um",
  Ytterbium: "ih ter bee um",
  Lutetium: "loo tee shee um",
  Hafnium: "haf nee um",
  Tantalum: "tan tuh lum",
  Tungsten: "tung sten",
  Rhenium: "ree nee um",
  Osmium: "oz mee um",
  Iridium: "ih rid ee um",
  Platinum: "plat in um",
  Gold: "gold",
  Mercury: "mur kyuh ree",
  Thallium: "thal ee um",
  Lead: "led",
  Bismuth: "biz muth",
  Polonium: "puh loh nee um",
  Astatine: "ass tuh teen",
  Radon: "ray don",
  Francium: "fran see um",
  Radium: "ray dee um",
  Actinium: "ack tin ee um",
  Thorium: "thor ee um",
  Protactinium: "pro tack tin ee um",
  Uranium: "yoo ray nee um",
  Neptunium: "nep too nee um",
  Plutonium: "ploo toh nee um",
  Americium: "am uh rish ee um",
  Curium: "cure ee um",
  Berkelium: "burk lee um",
  Californium: "kal ih for nee um",
  Einsteinium: "ine stine ee um",
  Fermium: "fur mee um",
  Mendelevium: "men duh lee vee um",
  Nobelium: "no bell ee um",
  Lawrencium: "luh ren see um",
  Rutherfordium: "ruth er ford ee um",
  Dubnium: "doob nee um",
  Seaborgium: "see borg ee um",
  Bohrium: "bore ee um",
  Hassium: "hass ee um",
  Meitnerium: "mite near ee um",
  Darmstadtium: "darm stat ee um",
  Roentgenium: "runt gen ee um",
  Copernicium: "koh per nee see um",
  Nihonium: "nee hoh nee um",
  Flerovium: "fluh roh vee um",
  Moscovium: "moss koh vee um",
  Livermorium: "liv er mor ee um",
  Tennessine: "ten uh seen",
  Oganesson: "oh guh ness on",
};
